# Generated by Django 4.2.13 on 2024-06-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_post_excerpt_post_updated_on_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
