# Generated by Django 4.2.13 on 2024-06-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
