# Generated by Django 5.0.6 on 2024-06-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_profile_bio_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
