# Generated by Django 5.0.6 on 2024-06-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
