# Generated by Django 4.2.13 on 2024-06-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersignup',
            old_name='date_signed_up',
            new_name='date_subscribed',
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
