# Generated by Django 4.2.13 on 2024-06-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_delete_newsletter'),
        ('about', '0003_newslettersignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSignup',
        ),
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='read',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_page.tag'),
            preserve_default=False,
        ),
    ]
