# Generated by Django 5.0.6 on 2024-06-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_message_collaboraterequest_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
